### PR TITLE
Create function to return __attribute in JSON format

### PR DESCRIPTION
**Pull request by keeganmdotcom**
I ran in to a case where a custom attribute for an Organization had an identifier that started with a number. This wasn't accessible from the Model, so I added in a function to return __attributes as a JSON dict.

This is my first attempt at forking & creating a pull request, please let me know if I do something incorrectly.

### CODE REVIEW

**Comment by matumaros** [comment]
Thank you for contributing!
I'm going to make some updates on your code and push them.
Is there any particular reason why the method is called "**json**"? If not then I would like to rename it to something more meaningful.

**Comment by keeganmdotcom** [comment]
Hi, thanks for accepting! No reason I called it json, it just made sense at the time. Thanks!

**Comment by matumaros** [comment]
Alright, I changed the name to "attributes_as_json", just to be more conform with the rest of the code (and PEP8). Have a look at the code and tell me if it's alright.

**Comment by keeganmdotcom** [comment]
Looks great. Thanks again.

**Pull request merged**
